//
//  MainViewController.swift
//  Subclass of CAPBridgeViewController that manually registers our
//  in-app native plugins with the Capacitor bridge.
//
//  Why this file exists:
//    Capacitor does NOT auto-discover plugin classes by scanning the
//    Objective-C runtime. At startup it reads `capacitor.config.json`'s
//    `packageClassList`, which is generated by `cap sync` from npm-installed
//    plugins only. Custom plugins that live inside the iOS app project
//    (like VolumeButtonPlugin) are never in that list, so the bridge never
//    learns about them — every JS call then rejects with
//      '"<jsName>" plugin is not implemented on ios'.
//
//  The fix: override capacitorDidLoad() and register the instance manually.
//  The storyboard's root view controller is pointed at this class instead
//  of the stock CAPBridgeViewController.
//

import UIKit
import Capacitor

class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        NSLog("[MainViewController] capacitorDidLoad — registering VolumeButtonPlugin")
        bridge?.registerPluginInstance(VolumeButtonPlugin())
    }
}
